### ISSUE TITLE
Support for bsz>1 and GQA

### ISSUE THREAD

**Issue by Ryanuppp** [mit-han-lab/Quest#8]
Great job! 
We found that Quest is implemented on the previous version of flashinfer and some common feature are not support currently.
* bsz > 1
* GQA
* CUDA graph 
Is there any plan to update to the latest version of flashinfer and provide these features?

**Comment by happierpig** [comment]
Hi @Ryanuppp ,

We are exploring a follow-up work after Quest, in which we plan to update these features.

**Comment by wjj19950828** [comment]
@happierpig Is GQA currently supported? The mainstream architectures, such as llama2/3 70b, are mainly GQA. It is very important to support this feature.

**Comment by Sakits** [comment]
Hi @Ryanuppp @wjj19950828 ,

Thank you for your interest in our work! 

We've updated the support for the latest Llama and Mistral models. Please check out our [latest commit](https://github.com/mit-han-lab/Quest/tree/dev/new_models) :)

**Comment by carriex** [comment]
Thanks for adding Llama and Mistral model! I was able to run the passkey evaluation [script](https://github.com/mit-han-lab/Quest/blob/main/scripts/passkey.sh). However I noticed that the model is not loaded with FlashAttention [here](https://github.com/mit-han-lab/Quest/blob/main/evaluation/passkey/passkey.py), and when I load it with FlashAttention, I encountered below error, likely due to transformers version mismatch. Could you let me know how to run QUEST with GQA models with FlashAttention? Thanks!!

```
    return self.flash_forward(
TypeError: LlamaFlashAttention2.forward() got an unexpected keyword argument 'padding_mask'
```

**Comment by carriex** [comment]
thanks for the updates! Is it also possible to run the kernel version for GQA models such as LLaMA-3.1-8B? 👀

**Comment by happierpig** [comment]
Hi @carriex ,

I'm sorry that the paper implementation of kernels does not support GQA. For efficiency comparison, it also makes sense to compare with the theoretical memory loading size.

**Comment by carriex** [comment]
Got it, thanks for getting back to me!
